
rewards_data = 'rewards.id as id,reward_origin,reward_origin_logo,background_image,logo,offer,offer_description,offer_type,company_name,cost,terms_and_conditions,expiry_date,link,contact,rating,cuisine,working_hours,website'


GET_ALL_REWARDS = f"SELECT {rewards_data} FROM rewards;"
GET_ALL_REWARDS_FILTERED = f"SELECT {rewards_data} FROM rewards WHERE reward_origin IN ("+"{})"
GET_ALL_REWARDS_WITH_LOCATIONS = f"SELECT {rewards_data} FROM rewards,rewards_and_locations where id=reward_id"
GET_ALL_REWARDS_WITH_LOCATIONS_FILTERED = f"SELECT {rewards_data} FROM rewards,rewards_and_locations where id=reward_id AND reward_origin IN ("+"{})"
GET_ALL_REWARDS_BY_PROGRAM = f"SELECT {rewards_data} FROM rewards where reward_origin = '"+"{}'"
GET_ALL_REWARDS_BY_COMPANY_NAME = f"SELECT {rewards_data} FROM rewards where company_name LIKE '"+"{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_COMPANY_NAME_FILTERED = f"SELECT {rewards_data} FROM rewards where company_name LIKE '"+"{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY = f"SELECT {rewards_data} FROM rewards where offer_type LIKE '%"+"{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY_FILTERED = f"SELECT {rewards_data} FROM rewards where offer_type LIKE '%"+"{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
COUNT_REWARDS = "SELECT COUNT(*) FROM rewards;"
COUNT_REWARDS_FILTERED = "SELECT COUNT(*) FROM rewards WHERE reward_origin IN ({});"
COUNT_REWARDS_WITH_LOCATIONS =  "SELECT COUNT(*) FROM rewards,rewards_and_locations where id=reward_id"
COUNT_REWARDS_WITH_LOCATIONS_FILTERED = "SELECT COUNT(*) FROM rewards,rewards_and_locations where id=reward_id AND reward_origin IN ({})"
COUNT_REWARDS_BY_PROGRAM = "SELECT COUNT(*) FROM rewards where reward_origin = '{}'"
COUNT_REWARDS_BY_COMPANY_NAME = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%'"
COUNT_REWARDS_BY_COMPANY_NAME_FILTERED = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%' AND reward_origin IN ({})"
COUNT_REWARDS_BY_CATEGORY = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%'"
COUNT_REWARDS_BY_CATEGORY_FILTERED = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%' AND reward_origin IN ({})"
GET_ALL_PROGRAMS = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards GROUP BY reward_origin;"
GET_ALL_PROGRAMS_FILTERED = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards WHERE reward_origin in ({}) GROUP BY reward_origin;"
GET_ALL_COMPANIES = "SELECT DISTINCT company_name from rewards;"
GET_ALL_COMPANIES_FILTERED = "SELECT DISTINCT company_name from rewards WHERE reward_origin IN ({});"
GET_ALL_CATEGORIES = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards GROUP BY offer_type;"
GET_ALL_CATEGORIES_FILTERED = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards WHERE reward_origin IN ({}) GROUP BY offer_type;"

GET_ALL_REWARD_LOCATIONS = "SELECT formatted_address,city,id,lat,lon FROM locations,rewards_and_locations WHERE locations.id=rewards_and_locations.location_id AND reward_id='{}'"
COUNT_REWARDS_BY_CITY = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city='{}'"
COUNT_REWARDS_BY_CITY_FILTERED = "SELECT COUNT(*) FROM rewards_and_locations, locations,rewards WHERE locations.id=location_id AND rewards.id=reward_id AND city='{}' AND reward_origin IN ({})"
GET_ALL_REWARDS_BY_CITY = f"SELECT {rewards_data} FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city ="+ "'{}'"
GET_ALL_REWARDS_BY_CITY_FILTERED = f"SELECT {rewards_data} FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city = '"+"{}' AND reward_origin IN ({})"
GET_ALL_CITIES = "SELECT COUNT(*) as count, city FROM rewards_and_locations,rewards, locations WHERE rewards.id=reward_id AND locations.id=location_id GROUP BY city"
GET_ALL_CITIES_FILTERED = "SELECT COUNT(*) as count, city FROM rewards_and_locations,rewards, locations WHERE locations.id=location_id AND rewards.id=reward_id AND reward_origin in ({}) GROUP BY city"

COUNT_REWARDS_BY_LOCATION_REGION = "SELECT count(offer) as count,formatted_address, lat,lon FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN  {} AND {} AND lon BETWEEN  {} AND {} group by lat,lon"
COUNT_REWARDS_BY_LOCATION_REGION_FILTERED = "SELECT count(offer) as count,formatted_address, lat,lon FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN  {} AND {} AND lon BETWEEN  {} AND {} AND reward_origin IN ({}) group by lat,lon"
GET_ALL_REWARDS_BY_LOCATION_REGION = f"SELECT {rewards_data} FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN "+"{} AND {} AND lon BETWEEN {} AND {} AND reward_origin IN ({}) GROUP BY lat,lon"
GET_ALL_REWARDS_BY_LOCATION = f"SELECT {rewards_data} FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ="+"{} AND lon ={}"
COUNT_REWARDS_BY_LOCATION = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={}"
GET_ALL_REWARDS_BY_LOCATION_FILTERED = f"SELECT {rewards_data} FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ="+"{} AND lon ={} AND reward_origin IN ({})"
COUNT_REWARDS_BY_LOCATION_FILTERED = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={} AND reward_origin IN ({})"

GET_UNIQUE_LOCATIONS_COORDINATES = "SELECT id, lat,lon FROM locations,rewards_and_locations WHERE id=location_id GROUP BY id"
GET_UNIQUE_LOCATIONS_COORDINATES_FILTERED = "SELECT locations.id, lat,lon FROM locations,rewards_and_locations,rewards WHERE locations.id=location_id AND rewards.id=reward_id AND reward_origin IN ({}) GROUP BY locations.id"
GET_REWARDS_BY_LOCATION_ID = f"SELECT {rewards_data} FROM rewards_and_locations, locations, rewards WHERE rewards.id = reward_id AND locations.id = location_id AND location_id = '"+"{}'"
GET_REWARDS_BY_LOCATION_ID_FILTERED = f"SELECT {rewards_data} FROM rewards_and_locations, locations, rewards WHERE rewards.id = reward_id AND locations.id = location_id AND location_id = '"+"{}' AND reward_origin IN ({})"

GET_LOCATION_BY_LOCATION_ID = "SELECT formatted_address,city,id,lat,lon FROM locations WHERE id = '{}'"