GET_ALL_REWARDS = "SELECT * FROM rewards;"
GET_ALL_REWARDS_FILTERED = "SELECT * FROM rewards WHERE reward_origin IN ({});"
GET_ALL_REWARDS_BY_PROGRAM = "SELECT * FROM rewards where reward_origin = '{}'"
GET_ALL_REWARDS_BY_COMPANY_NAME = "SELECT * FROM rewards where company_name LIKE '{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_COMPANY_NAME_FILTERED = "SELECT * FROM rewards where company_name LIKE '{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY = "SELECT * FROM rewards where offer_type LIKE '%{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY_FILTERED = "SELECT * FROM rewards where offer_type LIKE '%{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
COUNT_REWARDS = "SELECT COUNT(*) FROM rewards;"
COUNT_REWARDS_FILTERED = "SELECT COUNT(*) FROM rewards WHERE reward_origin IN ({});"
COUNT_REWARDS_BY_PROGRAM = "SELECT COUNT(*) FROM rewards where reward_origin = '{}'"
COUNT_REWARDS_BY_COMPANY_NAME = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%'"
COUNT_REWARDS_BY_COMPANY_NAME_FILTERED = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%' AND reward_origin IN ({})"
COUNT_REWARDS_BY_CATEGORY = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%'"
COUNT_REWARDS_BY_CATEGORY_FILTERED = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%' AND reward_origin IN ({})"
GET_ALL_PROGRAMS = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards GROUP BY reward_origin;"
GET_ALL_PROGRAMS_FILTERED = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards WHERE reward_origin in ({}) GROUP BY reward_origin;"
GET_ALL_COMPANIES = "SELECT DISTINCT company_name from rewards;"
GET_ALL_COMPANIES_FILTERED = "SELECT DISTINCT company_name from rewards WHERE reward_origin IN ({});"
GET_ALL_CATEGORIES = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards GROUP BY offer_type;"
GET_ALL_CATEGORIES_FILTERED = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards WHERE reward_origin IN ({}) GROUP BY offer_type;"
