GET_ALL_REWARDS = "SELECT * FROM rewards;"
GET_ALL_REWARDS_FILTERED = "SELECT * FROM rewards WHERE reward_origin IN ({});"
GET_ALL_REWARDS_BY_PROGRAM = "SELECT * FROM rewards where reward_origin = '{}'"
GET_ALL_REWARDS_BY_COMPANY_NAME = "SELECT * FROM rewards where company_name LIKE '{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_COMPANY_NAME_FILTERED = "SELECT * FROM rewards where company_name LIKE '{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY = "SELECT * FROM rewards where offer_type LIKE '%{}%' ORDER BY LOWER(company_name)"
GET_ALL_REWARDS_BY_CATEGORY_FILTERED = "SELECT * FROM rewards where offer_type LIKE '%{}%' AND reward_origin IN ({}) ORDER BY LOWER(company_name)"
COUNT_REWARDS = "SELECT COUNT(*) FROM rewards;"
COUNT_REWARDS_FILTERED = "SELECT COUNT(*) FROM rewards WHERE reward_origin IN ({});"
COUNT_REWARDS_BY_PROGRAM = "SELECT COUNT(*) FROM rewards where reward_origin = '{}'"
COUNT_REWARDS_BY_COMPANY_NAME = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%'"
COUNT_REWARDS_BY_COMPANY_NAME_FILTERED = "SELECT COUNT(*) FROM rewards where company_name LIKE '{}%' AND reward_origin IN ({})"
COUNT_REWARDS_BY_CATEGORY = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%'"
COUNT_REWARDS_BY_CATEGORY_FILTERED = "SELECT COUNT(*) FROM rewards where offer_type LIKE '%{}%' AND reward_origin IN ({})"
GET_ALL_PROGRAMS = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards GROUP BY reward_origin;"
GET_ALL_PROGRAMS_FILTERED = "SELECT COUNT(reward_origin) AS count, reward_origin,reward_origin_logo FROM rewards WHERE reward_origin in ({}) GROUP BY reward_origin;"
GET_ALL_COMPANIES = "SELECT DISTINCT company_name from rewards;"
GET_ALL_COMPANIES_FILTERED = "SELECT DISTINCT company_name from rewards WHERE reward_origin IN ({});"
GET_ALL_CATEGORIES = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards GROUP BY offer_type;"
GET_ALL_CATEGORIES_FILTERED = "SELECT COUNT(offer_type) AS count, offer_type FROM rewards WHERE reward_origin IN ({}) GROUP BY offer_type;"

GET_ALL_REWARD_LOCATIONS = "SELECT * FROM locations,rewards_and_locations WHERE locations.id=rewards_and_locations.location_id AND reward_id='{}'"
COUNT_REWARDS_BY_CITY = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city='{}'"
COUNT_REWARDS_BY_CITY_FILTERED = "SELECT COUNT(*) FROM rewards_and_locations, locations,rewards WHERE locations.id=location_id AND rewards.id=reward_id AND city='{}' AND reward_origin IN ({})"
GET_ALL_REWARDS_BY_CITY = "SELECT * FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city = '{}'"
GET_ALL_REWARDS_BY_CITY_FILTERED = "SELECT * FROM locations,rewards_and_locations,rewards WHERE rewards.id=reward_id AND locations.id=location_id AND city = '{}' AND reward_origin IN ({})"
GET_ALL_CITIES = "SELECT COUNT(*) as count, city FROM rewards_and_locations,rewards, locations WHERE rewards.id=reward_id AND locations.id=location_id GROUP BY city"
GET_ALL_CITIES_FILTERED = "SELECT COUNT(*) as count, city FROM rewards_and_locations,rewards, locations WHERE locations.id=location_id AND rewards.id=reward_id AND reward_origin in ({}) GROUP BY city"

COUNT_REWARDS_BY_LOCATION_REGION = "SELECT count(offer) as count,formatted_address, lat,lon FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN  {} AND {} AND lon BETWEEN  {} AND {} group by lat,lon"
COUNT_REWARDS_BY_LOCATION_REGION_FILTERED = "SELECT count(offer) as count,formatted_address, lat,lon FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN  {} AND {} AND lon BETWEEN  {} AND {} AND reward_origin IN ({}) group by lat,lon"
GET_ALL_REWARDS_BY_LOCATION_REGION = "SELECT * FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat BETWEEN {} AND {} AND lon BETWEEN {} AND {} AND reward_origin IN ({}) GROUP BY lat,lon"
GET_ALL_REWARDS_BY_LOCATION = "SELECT * FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={}"
COUNT_REWARDS_BY_LOCATION = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={}"
GET_ALL_REWARDS_BY_LOCATION_FILTERED = "SELECT * FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={} AND reward_origin IN ({})"
COUNT_REWARDS_BY_LOCATION_FILTERED = "SELECT COUNT(*) FROM locations,rewards_and_locations,rewards WHERE locations.id = location_id AND rewards.id = reward_id AND lat ={} AND lon ={} AND reward_origin IN ({})"