class Reward:
    def __init__(self):
        self.rewardOrigin=''
        self.rewardOriginLogo=''
        self.backgroundImage=''
        self.logo=''
        self.offer=''
        self.offerDescription=''
        self.offerType=''
        self.companyName=''
        self.cost=''
        self.termsAndConditions=''
        self.location=''
        self.expiryDate=''
        self.link=''
        self.contact=''
        self.rating=''
        self.cuisine=''
        self.workingHours=''
